sudo: required
services:
  - docker

before_install:
  - docker build -t yokanand/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yokanand/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  app: "docker"
  region: "us-west-2"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-697735877338"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
